spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/customer_service
    username: postgres
    password: 123

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8083